# Generated by Django 5.1.3 on 2024-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='emergency_contact_number',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='emergency_contact',
            field=models.JSONField(default=dict),
        ),
    ]
