# Generated by Django 5.1.3 on 2024-12-08 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_professionalsummaryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIdentityDetailsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
