# Generated by Django 5.1.3 on 2024-12-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_experiences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
