# Generated by Django 5.1.3 on 2025-01-05 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('avg_hours_per_day', models.DurationField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('regularise_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('regularise_note', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='attendance_tracker.attendance')),
            ],
        ),
    ]
